import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward'
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward'
import Chip from '@mui/material/Chip'
import Tooltip from '@mui/material/Tooltip'

import type { Usage } from '../types'

/**
 * Token accounting for a run: prompt tokens in, generated tokens out, and how
 * many model calls the pipeline made (one per chunk, plus any merge pass).
 */
export default function UsageChips({ usage }: { usage: Usage }) {
  const total = usage.input_tokens + usage.output_tokens
  if (!total) {
    return (
      <Tooltip title="This provider did not return token counts for the run">
        <Chip size="small" variant="outlined" label="tokens not reported" />
      </Tooltip>
    )
  }
  return (
    <>
      <Tooltip title="Input tokens - prompt, template and document text sent to the model">
        <Chip
          size="small"
          variant="outlined"
          color="primary"
          icon={<ArrowUpwardIcon />}
          label={`${usage.input_tokens.toLocaleString()} in`}
        />
      </Tooltip>
      <Tooltip title="Output tokens - text generated by the model">
        <Chip
          size="small"
          variant="outlined"
          color="secondary"
          icon={<ArrowDownwardIcon />}
          label={`${usage.output_tokens.toLocaleString()} out`}
        />
      </Tooltip>
      <Tooltip title={`${total.toLocaleString()} tokens total across ${usage.calls} model call(s)`}>
        <Chip
          size="small"
          variant="outlined"
          label={`${usage.calls} call${usage.calls === 1 ? '' : 's'}`}
        />
      </Tooltip>
    </>
  )
}
